services:
  app-prod:
    image: josemokeni/my-wallets-nextjs
    env_file:
      - .env
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mywallets.rule=Host(`mywallets.josemokeni.cloud`)"
      - "traefik.http.services.mywallets.loadbalancer.server.port=3000"
      - "traefik.http.routers.mywallets.entrypoints=websecure"
      - "traefik.http.routers.mywallets.tls=true"
      - "traefik.http.routers.mywallets.tls.certresolver=leresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - traefik-public
      - default
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: mywallets
      POSTGRES_PASSWORD: securedpassword
      POSTGRES_DB: expense_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 --cleanup --rolling-restart
    environment:
      - WATCHTOWER_TIMEOUT=60s
      - WATCHTOWER_LABEL_ENABLE=true
    networks:
      - default
    restart: unless-stopped
volumes:
  pgdata:
    driver: local

networks:
  traefik-public:
    external: true
